#!/bin/bash

# Quick Setup Script for film-react-nest CI/CD
# This script provides a quick reference for setting up the CI/CD pipeline

echo "╔════════════════════════════════════════════════════════════════════════╗"
echo "║         film-react-nest CI/CD Pipeline Setup                          ║"
echo "╚════════════════════════════════════════════════════════════════════════╝"
echo ""

echo "📋 Информация о конфигурации:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Домен:              inikotinthegame.nomorepartiessbs.ru"
echo "  IP сервера:         158.160.133.7"
echo "  Пользователь:       inikotin"
echo "  Тип ключа:          ssh-ed25519"
echo "  Платформа:          Yandex Cloud (cloud-config)"
echo ""

echo "✅ Созданные файлы:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📁 GitHub Actions Workflows:"
echo "  ✓ .github/workflows/build-and-push.yml"
echo "    └─ Сборка Docker образов и публикация в ghcr.io"
echo "    └─ Триггер: push в main и review-2"
echo "    └─ Собирает: backend, frontend, nginx"
echo ""
echo "  ✓ .github/workflows/deploy.yml"
echo "    └─ Развертывание на сервер через SSH"
echo "    └─ Триггер: после успешного build-and-push"
echo "    └─ Выполняет: scripts/deploy.sh на сервере"
echo ""

echo "📁 Deploy Scripts:"
echo "  ✓ scripts/deploy.sh"
echo "    └─ Основной скрипт развертывания"
echo "    └─ Pull образов из GHCR"
echo "    └─ Перезапуск контейнеров"
echo "    └─ Health check"
echo ""
echo "  ✓ scripts/setup-server.sh"
echo "    └─ Подготовка сервера"
echo "    └─ Создание директорий и логов"
echo "    └─ Опциональный systemd сервис"
echo ""

echo "📁 Документация:"
echo "  ✓ DEPLOYMENT.md"
echo "    └─ Полное руководство по настройке (10 частей)"
echo "    └─ Конфигурация GitHub Secrets"
echo "    └─ Подготовка сервера"
echo "    └─ Troubleshooting"
echo ""
echo "  ✓ CI_CD_SETUP.md"
echo "    └─ Быстрый чеклист настройки"
echo "    └─ Этап 1: GitHub Repository Setup"
echo "    └─ Этап 2: Server Setup"
echo "    └─ Этап 3: Тестирование"
echo "    └─ Этап 4: CI/CD Pipeline"
echo ""

echo "🔑 GitHub Secrets для добавления:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. SSH_PRIVATE_KEY"
echo "   └─ Приватный ключ для подключения к серверу"
echo "   └─ Используйте существующий или создайте новый"
echo ""
echo "2. SERVER_HOST"
echo "   └─ 158.160.133.7"
echo ""
echo "3. SERVER_USER"
echo "   └─ inikotin"
echo ""
echo "4. SERVER_PORT"
echo "   └─ 22"
echo ""

echo "🚀 Быстрый старт:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Шаг 1: Добавьте секреты в GitHub"
echo "  Repository → Settings → Secrets and variables → Actions"
echo "  Добавьте 4 секрета (см. выше)"
echo ""
echo "Шаг 2: Подготовьте сервер"
echo "  ssh inikotin@158.160.133.7"
echo "  cd ~"
echo "  git clone https://github.com/i-nikotin-THEGAME/film-react-nest.git"
echo "  cd film-react-nest"
echo "  bash scripts/setup-server.sh"
echo ""
echo "Шаг 3: Протестируйте"
echo "  bash scripts/deploy.sh"
echo ""
echo "Шаг 4: Запустите CI/CD"
echo "  git push origin main"
echo "  → Workflow автоматически сработает"
echo ""

echo "📚 Документация:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Для полной информации читайте:"
echo "  • DEPLOYMENT.md     - Полное руководство (10 частей)"
echo "  • CI_CD_SETUP.md    - Быстрый чеклист"
echo ""
echo "SSH на сервер:"
echo "  ssh inikotin@158.160.133.7"
echo ""
echo "Просмотр логов на сервере:"
echo "  tail -f ~/deployment.log"
echo "  docker-compose logs -f backend"
echo "  docker-compose logs -f frontend"
echo ""

echo "╔════════════════════════════════════════════════════════════════════════╗"
echo "║ ✅ CI/CD Pipeline готов! Следуйте инструкциям выше для начала         ║"
echo "╚════════════════════════════════════════════════════════════════════════╝"
echo ""
